(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



VerzeichnungsGraph[PolynomFunktion_]:=Module[{RIstNormiert, RSollNormiert,V, WertePaare, VWerte, WertePaareBisEins},
RSollNormiert = Range[0.001,2,0.001] ;
RIstNormiert = PolynomFunktion/@RSollNormiert;
(*V = Function[x,{x[[1]],(x[[1]]-x[[2]])*100/x[[1]]}]/@WertePaare;*)
V = Function[r,(PolynomFunktion[r]-r)*100/r];
VWerte = V/@RSollNormiert;
WertePaare =Partition[Riffle[RIstNormiert,VWerte],2];
WertePaareBisEins = Select[WertePaare,#[[1]]<= 1&];
(*ListPlot[WertePaare,DataRange \[Rule] {0,1}]
writeLog["PolynomFunktion: ", Plot[PolynomFunktion[r],{r,0,1}]];
writeLog["Gemeinsam: ", Show[Plot[PolynomFunktion[r],{r,0,1},PlotStyle\[Rule]Red],Plot[r,{r,0,1}]]];*)
Return[WertePaareBisEins];
]
