(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



InvertierePolynom[Funktion_]:=Module[{XWerte,YWerte, NeueFunction, FormatierteFunction},
XWerte = Range[0,1,0.001] ;
YWerte = Funktion/@XWerte;
NeueFunction =Fit[Partition[Riffle[YWerte,XWerte],2],{x,x^3,x^5,x^7},x];
Return[NeueFunction];
];




